Removing debconf, too many issues.

diff --git a/builders/emby-server/debfiles/prerm b/builders/emby-server/debfiles/prerm
--- a/builders/emby-server/debfiles/prerm
+++ b/builders/emby-server/debfiles/prerm
@@ -20,9 +20,6 @@ PROGRAMDATA=${EMBY_DATA-/var/lib/$NAME}
 
 case "$1" in
   remove|upgrade|deconfigure)
-    . /usr/share/debconf/confmodule
-    db_version 2.0
-    db_capb backup
     # try and figure out if emby is running
     PIDFILE=`find /var/run -name "emby*.pid" -print -quit`
     [ -n "$PIDFILE" ] && EMBY_PID=`cat ${PIDFILE} 2> /dev/null || true`
@@ -31,14 +28,15 @@ case "$1" in
       echo "Stopping Emby Server!"
       # try graceful termination;
       # Figure out how to start/stop emby-server daemon
-      if which service >/dev/null 2>&1; then
-        _service_invoke="service ${NAME}"
+      if which systemctl > /dev/null 2>&1; then
+        sysetemctl stop ${NAME} 2>/dev/null || true
+      elif which service >/dev/null 2>&1; then
+        service ${NAME} stop 2>/dev/null || true
       elif which invoke-rc.d >/dev/null 2>&1; then
-        _service_invoke="invoke-rc.d ${NAME}"
+        invoke-rc.d ${NAME} stop 2>/dev/null || true
       else
-        _service_invoke=/etc/init.d/${NAME}
+        /etc/init.d/${NAME} stop 2>/dev/null || true
       fi
-      ${_service_invoke} stop 2>/dev/null || true
       # if emby is still running, kill it
       if kill -0 $EMBY_PID > /dev/null 2>&1; then
         CPIDS=$(pgrep -P $EMBY_PID)
@@ -48,9 +46,7 @@ case "$1" in
       sleep 1
       # if it's still running, show error
       if kill -0 $EMBY_PID > /dev/null; then
-        db_fset $NAME/old-running seen false || true
-        db_input critical $NAME/old-running || true
-        db_go || true
+        echo "Could not successfully stop EmbyServer, please do so before uninstalling."
         exit 1
       else
         [ -f $PIDFILE ] && rm $PIDFILE
