Added wily build. Fixed maintainers scripts.

diff --git a/emby-builder/debfiles/bin/emby-server b/emby-builder/debfiles/bin/emby-server
--- a/emby-builder/debfiles/bin/emby-server
+++ b/emby-builder/debfiles/bin/emby-server
@@ -15,9 +15,9 @@ LOG_FILE=/var/log/${NAME}.log
 
 # Source Emby server user configuration overrides
 if [ -f $CONF_FILE ]; then
-    . $CONF_FILE
+  . $CONF_FILE
 else
-    echo "${CONF_FILE} not found using default settings.";
+  echo "${CONF_FILE} not found using default settings.";
 fi
 
 # Run as username
@@ -48,17 +48,17 @@ MONO_EXEC_OPTS=$MONO_OPTS
 
 # ffmpeg
 FFMPEG_BIN=$(which ffmpeg)
-[ -n "$FFMPEG_BIN" ] && FFMPEG_OPTS="-ffmpeg $FFMPEG_BIN" 
+[ -n "$FFMPEG_BIN" ] && FFMPEG_OPTS="-ffmpeg $FFMPEG_BIN"
 
 # ffprobe
 FFPROBE_BIN=$(which ffprobe)
-[ -n "$FFPROBE_BIN" ] && FFPROBE_OPTS="-ffprobe $FFPROBE_BIN" 
+[ -n "$FFPROBE_BIN" ] && FFPROBE_OPTS="-ffprobe $FFPROBE_BIN"
 
 # restart function
 RESTART_OPTS="-restartpath ${EMBY_PATH}/restart.sh"
 
 # Emby options
-EMBY_OPTS="$PROGRAMDATA_OPT $FFMPEG_OPTS $FFPROBE_OPTS $RESTART_OPTS $EMBY_ADD_OPTS"               
+EMBY_OPTS="$PROGRAMDATA_OPT $FFMPEG_OPTS $FFPROBE_OPTS $RESTART_OPTS $EMBY_ADD_OPTS"
 
 PID_PATH=`dirname $PIDFILE`
 
@@ -67,27 +67,27 @@ PID_PATH=`dirname $PIDFILE`
 
 # Create programdata  directory if not exist and ensure the emby user can write to it
 if [ ! -d $PROGRAMDATA ]; then
-    mkdir -p $PROGRAMDATA
+  mkdir -p $PROGRAMDATA
 fi
 
 # Set right permission for directories
 DATA_CURRENT_USER=`ls -lad $PROGRAMDATA | awk '{print $3}'`
 
 if [ "$DATA_CURRENT_USER" != "$USER" ]; then
-    chown -R $USER.$GROUP $PROGRAMDATA
+  chown -R $USER.$GROUP $PROGRAMDATA
 fi
 
 case "$1" in
-    start)
-        echo $$ > $PIDFILE
-        exec su -s /bin/sh -c 'exec "$0" "$@"' $USER -- \
-        env $MONO_EXEC_ENV $MONO_EXEC $MONO_EXEC_OPTS $EMBY_EXEC $EMBY_OPTS > $LOG_FILE 2>&1  
-        ;;
-    clear)
+  start)
+    echo $$ > $PIDFILE
+    exec su -s /bin/sh -c 'exec "$0" "$@"' $USER -- \
+    env $MONO_EXEC_ENV $MONO_EXEC $MONO_EXEC_OPTS $EMBY_EXEC $EMBY_OPTS > $LOG_FILE 2>&1
+    ;;
+  clear)
     [ -e $PIDFILE ] && rm -rf $PIDFILE
-        ;;
-    *)
-        echo "Usage: $SCRIPTNAME {start|clear}" >&2
-        exit 3
+    ;;
+  *)
+    echo "Usage: $SCRIPTNAME {start|clear}" >&2
+    exit 3
     ;;
 esac
diff --git a/emby-builder/debfiles/emby-server.init b/emby-builder/debfiles/emby-server.init
--- a/emby-builder/debfiles/emby-server.init
+++ b/emby-builder/debfiles/emby-server.init
@@ -2,7 +2,7 @@
 ### BEGIN INIT INFO
 # Provides:          emby-server
 # Required-Start:    $remote_fs $local_fs $network
-# Required-Stop:     $remote_fs $local_fs $network 
+# Required-Stop:     $remote_fs $local_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: starts instance of Emby
@@ -28,62 +28,61 @@ DEFAULT_FILE=/etc/default/${NAME}
 
 # Source Emby server user configuration overrides
 if [ -f $CONF_FILE ]; then
-    . $CONF_FILE
+  . $CONF_FILE
 else
-    echo "${CONF_FILE} not found using default settings.";
+  echo "${CONF_FILE} not found using default settings.";
 fi
 
 # Path of emby binary
 EMBYSERVER=/usr/bin/emby-server
 PIDFILE=${EMBY_PIDFILE-/var/run/emby-server.pid}
 
-
 case "$1" in
-    start)
-        log_daemon_msg "Starting $NAME daemon"
-        if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
-            log_daemon_msg "apparently already running"
-            log_end_msg 0
-            exit 0
-        fi
-        exec $EMBYSERVER start &
+  start)
+    log_daemon_msg "Starting $NAME daemon"
+    if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
+      log_daemon_msg "apparently already running"
+      log_end_msg 0
+      exit 0
+    fi
+    exec $EMBYSERVER start &
     sleep 2
-        if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
-            log_end_msg 0
-        else
-            log_end_msg 1
-        fi
-        ;;
-    stop)
-        log_daemon_msg "Stopping $NAME daemon"
-        if [ ! -s $PIDFILE ] || ! kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
-            [ -e $PIDFILE ] && rm -rf $PIDFILE
-            log_success_msg "apparently already stopped"
-            log_end_msg 0
-            exit 0
-        fi
-        PID=`cat $PIDFILE`
-        CPIDS=$(pgrep -P $PID) 
-        sleep 2 && kill -KILL $CPIDS 
-        kill -TERM $CPIDS > /dev/null 2>&1
-        sleep 2
-        if ! kill -0 $PID >/dev/null 2>&1; then
-            rm -rf $PIDFILE
-            log_end_msg 0
-        else
-            log_end_msg 1
-        fi
-        ;;
-    status)
-        status_of_proc -p $PIDFILE "$EMBYSERVER" "$NAME" 
-        exit $? # notreached due to set -e
-        ;;
-    restart|force-reload)
-        $0 stop || exit $?
-        $0 start || exit $?
-        ;;
-    *)
-        echo "Usage: /etc/init.d/emby-server {start|stop|status|restart|force-reload}" >&2
-        exit 3
+    if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
+      log_end_msg 0
+    else
+      log_end_msg 1
+    fi
+    ;;
+  stop)
+    log_daemon_msg "Stopping $NAME daemon"
+    if [ ! -s $PIDFILE ] || ! kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
+      [ -e $PIDFILE ] && rm -rf $PIDFILE
+      log_success_msg "apparently already stopped"
+      log_end_msg 0
+      exit 0
+    fi
+    PID=`cat $PIDFILE`
+    CPIDS=$(pgrep -P $PID)
+    sleep 2 && kill -KILL $CPIDS
+    kill -TERM $CPIDS > /dev/null 2>&1
+    sleep 2
+    if ! kill -0 $PID > /dev/null 2>&1; then
+      rm -rf $PIDFILE
+      log_end_msg 0
+    else
+      log_end_msg 1
+    fi
+    ;;
+  status)
+    status_of_proc -p $PIDFILE "$EMBYSERVER" "$NAME"
+    exit $? # notreached due to set -e
+    ;;
+  restart|force-reload)
+    $0 stop || exit $?
+    $0 start || exit $?
+    ;;
+  *)
+    echo "Usage: /etc/init.d/emby-server {start|stop|status|restart|force-reload}" >&2
+    exit 3
     ;;
 esac
